# Generated by Django 5.2.4 on 2025-07-28 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignboardFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('additional_cost_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SignboardSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('width_feet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height_feet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('area_sqft', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='SignboardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('material', models.CharField(max_length=100)),
                ('price_per_sqft', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='signboards/types/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignboardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('business_name', models.CharField(max_length=200)),
                ('text_content', models.TextField()),
                ('font_preferences', models.CharField(blank=True, max_length=200)),
                ('color_preferences', models.CharField(blank=True, max_length=200)),
                ('logo_upload', models.ImageField(blank=True, null=True, upload_to='signboards/logos/')),
                ('design_file', models.FileField(blank=True, null=True, upload_to='signboards/designs/')),
                ('special_requirements', models.TextField(blank=True)),
                ('installation_required', models.BooleanField(default=True)),
                ('installation_address', models.TextField()),
                ('contact_phone', models.CharField(max_length=15)),
                ('preferred_installation_date', models.DateField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('installation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('urgency', models.CharField(choices=[('standard', 'Standard (7-10 days)'), ('urgent', 'Urgent (3-5 days)'), ('express', 'Express (1-2 days)')], default='standard', max_length=20)),
                ('urgency_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('quote_requested', 'Quote Requested'), ('quote_sent', 'Quote Sent'), ('approved', 'Approved'), ('in_production', 'In Production'), ('ready_for_installation', 'Ready for Installation'), ('installing', 'Installing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='quote_requested', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('finish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signboards.signboardfinish')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signboards.signboardsize')),
                ('signboard_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signboards.signboardtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignboardGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='signboards/gallery/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signboard_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signboards.signboardtype')),
            ],
            options={
                'verbose_name_plural': 'Signboard Gallery',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
