# Generated by Django 5.2.4 on 2025-08-02 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorDesigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='designer_profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='DesignerGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='designer_galleries/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='interior.interiordesigner')),
            ],
        ),
    ]
