# Generated by Django 5.2.4 on 2025-07-28 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('license_number', models.CharField(max_length=50)),
                ('license_expiry', models.DateField()),
                ('experience_years', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('is_available', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('languages_spoken', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_model', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=10)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('ac_available', models.BooleanField(default=True)),
                ('gps_enabled', models.BooleanField(default=True)),
                ('insurance_valid_until', models.DateField()),
                ('pollution_certificate_valid_until', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.CharField(max_length=100)),
                ('base_rate_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('base_rate_per_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/types/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=20, unique=True)),
                ('booking_type', models.CharField(choices=[('hourly', 'Hourly Rental'), ('daily', 'Daily Rental'), ('one_way', 'One Way Trip'), ('round_trip', 'Round Trip'), ('airport_transfer', 'Airport Transfer')], max_length=20)),
                ('pickup_location', models.TextField()),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('dropoff_location', models.TextField(blank=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('contact_phone', models.CharField(max_length=15)),
                ('passenger_count', models.PositiveIntegerField()),
                ('special_requirements', models.TextField(blank=True)),
                ('estimated_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('distance_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('assigned', 'Driver Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_rating', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('driver_rating', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclebooking')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicletype'),
        ),
    ]
