# Generated by Django 5.2.4 on 2025-08-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='expertise',
            field=models.CharField(choices=[('carpenter', 'Carpenter'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('driver', 'Driver'), ('barber', 'Barber'), ('cleaner', 'Cleaner'), ('gardner', 'Gardner'), ('welder', 'Welder'), ('pipe_fitter', 'Pipe Fitter'), ('mechanic', 'Mechanic')], default='carpenter', max_length=30),
        ),
    ]
